before:
  hooks:
    - go mod tidy
    - go mod vendor

labels:
  - key: org.opencontainers.image.title
    value: "{{ .ProjectName }}"
  - key: org.opencontainers.image.description
    value: "{{ .ProjectName }}"
  - key: org.opencontainers.image.url
    value: "https://github.com/halkyon/{{ .ProjectName }}"
  - key: org.opencontainers.image.source
    value: "https://github.com/halkyon/{{ .ProjectName }}"
  - key: org.opencontainers.image.version
    value: "{{ .Version }}"
  - key: org.opencontainers.image.created
    value: "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
  - key: org.opencontainers.image.revision
    value: "{{ .FullCommit }}"
  - key: org.opencontainers.image.licenses
    value: MIT

docker_manifests:
  - name_template: halkyon/{{ .ProjectName }}:{{ .Version }}
    images:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}
    images:
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: halkyon/{{ .ProjectName }}:latest
    images:
      - halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/halkyon/{{ .ProjectName }}:latest
    images:
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-armv6
      - ghcr.io/halkyon/{{ .ProjectName }}:{{ .Version }}-arm64v8

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums_sha256.txt
  algorithm: sha256

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign"
      - "${artifact}"
    artifacts: images
    output: true

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  filters:
    exclude:
      - "^github-action"
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
